version: '3.8'
services:
# web service HTML app
  web:
    # context to build Dockerfile
    build: .
    # Container name
    container_name: clickfast
    # Map port 8080 on the host to port 80 in the container
    ports:
      - "8080:80"
